In [1]:
import os
print(os.getcwd())

C:\Users\tejas\OneDrive\Desktop\DRG_project\notebooks

In [2]:
import os

print(os.path.exists(r"C:\Users\tejas\OneDrive\Desktop\DRG_project\data\raw\consumption_d.csv"))

True

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\tejas\OneDrive\Desktop\DRG_project\data\raw\consumption_d.csv")

In [4]:
df["GMT"] = pd.to_datetime(df["GMT"])

df.head()

,GMT,D0000,D0001,D0002,D0003,D0004,D0005,D0006,D0007,D0008,...,D1015,D1016,D1017,D1018,D1019,D1020,D1021,D1022,D1023,D1024
0,2011-11-23 09:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-11-23 09:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-11-23 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-11-23 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-11-23 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df.dtypes.head())

GMT      datetime64[ns]
D0000           float64
D0001           float64
D0002           float64
D0003           float64
dtype: object

In [6]:
print(df["GMT"].min())
print(df["GMT"].max())

2011-11-23 09:00:00
2014-02-28 00:00:00

In [7]:
duplicates = df.duplicated().sum()

print("Duplicates:", duplicates)

Duplicates: 0

In [8]:
df = df.drop_duplicates()

In [9]:
missing = df.isnull().sum().sum()

print("Total Missing Values:", missing)

Total Missing Values: 9070661

In [10]:
df_long = df.melt(
    id_vars=["GMT"],
    var_name="household_id",
    value_name="consumption_kwh"
)

df_long.head()

                  GMT household_id  consumption_kwh
0 2011-11-23 09:00:00        D0000              NaN
1 2011-11-23 09:30:00        D0000              NaN
2 2011-11-23 10:00:00        D0000              NaN
3 2011-11-23 10:30:00        D0000              NaN
4 2011-11-23 11:00:00        D0000              NaN

In [11]:
df_long.rename(
    columns={"GMT":"datetime"},
    inplace=True
)

In [12]:
df_long.shape

(40720175, 3)

In [13]:
df_long = df_long.dropna()

In [14]:
df_long.shape

(31649514, 3)

In [15]:
(df_long["consumption_kwh"] < 0).sum()

np.int64(0)

In [17]:
df_long["consumption_kwh"].describe()

count    3.164951e+07
mean     1.990504e-01
std      2.657034e-01
min      0.000000e+00
25%      5.700000e-02
50%      1.130000e-01
75%      2.280000e-01
max      7.567000e+00
Name: consumption_kwh, dtype: float64

In [18]:
df_long.to_csv("C:/Users/tejas/OneDrive/Desktop/DRG_project/data/processed/clean_consumption.csv", index=False)

In [19]:
df_long.shape

(31649514, 3)